### ISSUE TITLE
Poor performance with high brush sizes

### ISSUE THREAD

**Issue by ettiSurreal** [outobugi/Terrain3D#178] opened 2023-08-06 15:03 UTC
Here's a video comparing performance at different brush sizes.

https://github.com/outobugi/Terrain3D/assets/98223724/f1bd3c17-7197-4a1e-b5b1-95a122aac8af

Quickly tried Unreal's built in terrain editor and it does perform better at seemingly 4x the brush size (assuming I'm right about the units). Whatever the case a performance improvement when drawing at some point in the future is definitely possible and would be nice to have.

**Comment by Saul2022** [comment] 2023-08-06 15:25
Happen’s the same with me, it mainly because it painted on the cpu unlike using the gpu see  https://github.com/outobugi/Terrain3D/issues/174

**Comment by ettiSurreal** [comment] 2023-08-06 15:33
> see #174
Ah, i thought that was about painting on the textures and not terrain for drawing/sculpting.

**Comment by TokisanGames** [comment] 2023-08-06 17:26
This is indeed a duplicate of #174. All sculpting, texturing, coloring, roughness are painting operations. All heightmap terrain editors are just fancy painting apps.

BTW, if you're going to use the terrain stamps turn off jitter in the advanced brush settings.
Also in the video you are painting an area 600m across.

**Closed by TokisanGames** 2023-08-06 17:26 UTC
Labels: duplicate
