### ISSUE TITLE
Adding surfaces causes freeze on load only during runtime

### ISSUE THREAD

**Issue by QueenOfSquiggles** [outobugi/Terrain3D#155] opened 2023-07-24 01:31 UTC
With the current latest release, on Manjaro Linux, Godot 4.1 Stable Mono, basically everything works correctly, but adding a surface texture to the terrain causes the game to freeze when running. Specifically it hitches somewhere in the scene loading process. In my case the scene is being loaded asynchronously and the remote scene tree shows that the terrain scene is not successfully loaded. None of this is an issue where there are no surface textures assigned. Example of textures used for testing attached.

Note, I know these textures are not legal to use for the purposes of a released game, I'm only using them as placeholders to test systems and make sure everything works before putting in the work to make my own materials
[SurfaceTextures.zip](https://github.com/outobugi/Terrain3D/files/12140938/SurfaceTextures.zip)

I did attempt to find some kind of console log from Terrain3D, but I couldn't get anything to show. Even running the program from the terminal didn't prove helpful.

I'm not quite sure what could be the problem, but hopefully this helps to make this plugin a bit better?

**Comment by TokisanGames** [comment] 2023-07-24 05:31
Thanks for the report.

> With the current latest release

Please use the master branch for bug testing. Many bugs have been fixed.

> adding a surface texture to the terrain causes the game to freeze when running. Specifically it hitches somewhere in the scene loading process. In my case the scene is being loaded asynchronously and the remote scene tree shows that the terrain scene is not successfully loaded. 

Please elaborate on exactly what you are doing. If it's code based, show code. And test with master. Make sure this isn't a duplicate of #147.

> Example of textures used for testing attached.

Your textures are not the right format. See the wiki for instructions on setting up textures.

> I did attempt to find some kind of console log from Terrain3D, but I couldn't get anything to show. Even running the program from the terminal didn't prove helpful.

Most likely a duplicate of #147.

**Comment by TokisanGames** [comment] 2023-07-25 14:41
> I did attempt to find some kind of console log from Terrain3D, but I couldn't get anything to show. 

Also this requires running the _console.exe version of godot, which you should always be doing as a gamedev.

Our logs print to the console, and you can get 10x more logs if you increase the debug level documented [in the wiki](https://github.com/outobugi/Terrain3D/wiki/Troubleshooting#debug-logs)

Closing as the texture format is a key problem and any crash was likely already fixed. If the issue persists in the main branch after textures are the right format, we can reopen.

**Closed by TokisanGames** 2023-07-25 14:41 UTC
Labels: not a bug
